steps:
# Step 1: Install npm dependencies
- name: 'node:22'
  entrypoint: 'npm'
  args: ['install']

# Step 2: Build the frontend application, creating the /dist directory
- name: 'node:22'
  entrypoint: 'npm'
  args: ['run', 'build']

# Step 3: Build the Docker image, which will now include the /dist directory
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/app-project-468120/frontend-service', '-f', 'Dockerfile.frontend', '.']

images:
- 'gcr.io/app-project-468120/frontend-service'
